# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c5a8722065852c52793a86bdc073d73d974ae9fa3dc9df2b23f4ae3591db824681462369337321545044351ebf2a92fb78645adcd7737641c1c7119f986d199

test:
  secret_key_base: de215d3f812939d36a97f700fc63123a8e70b9b3579a6c60b8af431baa622a187a13ebead1546553abe4ae68529fa75e2252ea76828b67d683a372dbabd31aa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
